version: "3"
services:
  ial-core-fe:
    image: ial-core-fe
    build:
      context: ./ial-core-fe
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - ial-microfrontend

  ial-get-fe:
    image: ial-get-fe
    build:
      context: ./ial-get-fe
      dockerfile: Dockerfile
    ports:
      - "5300:80"
    networks:
      - ial-microfrontend

  ial-svg-fe:
    image: ial-svg-fe
    build:
      context: ./ial-svg-fe
      dockerfile: Dockerfile
    ports:
      - "5200:80"
    networks:
      - ial-microfrontend

networks:
  ial-microfrontend:
    driver: bridge
