version: '3.8'
services:
  ial-core-fe:
    build: ./ial-core-fe
    ports:
      - "80:80"
    networks:
      - microfrontend-network

  ial-get-fe:
    build: ./ial-get-fe
    ports:
      - "81:80"
    networks:
      - microfrontend-network

  ial-svg-fe:
    build: ./ial-svg-fe
    ports:
      - "82:80"
    networks:
      - microfrontend-network

networks:
  microfrontend-network:
    driver: bridge
